#pragma once

enum class Opcode : uint16_t {
    MESSAGE = 1,

    CMSG_PING = 2,
    SMSG_PONG = 3,

    CMSG_HELLO = 4,
    SMSG_HELLO_RES = 5,

    CMSG_DATABASE_ASYNC_EXAMPLE = 6,
    SMSG_DATABASE_ASYNC_EXAMPLE = 7,

    CMSG_DATABASE_SYNC_EXAMPLE = 8,
    SMSG_DATABASE_SYNC_EXAMPLE = 9,

    CMSG_DATABASE_ASYNC_UPDATE = 10,
    SMSG_DATABASE_ASYNC_UPDATE = 11,
};